repository:
  name: emacs.d
  description: Personal GNU Emacs configuration
  homepage: https://brsvh.org/emacs.d
  topics: dotfiles, emacs-configuration, nixos-configuration
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  
  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
