name: Configuration - CI

on:
  push:
    paths:
      - 'org/**.org'
  pull_request:
    paths:
      - 'org/**.org'
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: nixbuild/nix-quick-install-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix Store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: ${{ runner.os }}-nix-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: ${{ runner.os }}-nix-
          purge: true
          purge-created: 604800

      - name: Check flake
        run: nix flake check

      - name: Update dependent packages
        run: nix run .#lock --impure

      - name: Check dependent packages
        run: nix build .#emacsD.depsCheck --print-build-logs

      - name: Check changed files
        uses: tj-actions/verify-changed-files@v17
        id: check-changed-files
        with:
          files: 'elpa/**'

      - name: Lock updates of dependent packages
        if: steps.check-changed-files.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(elpa): bump version"
          file_pattern: 'elpa/**'

  build:
    name: Build
    needs: [check]
    strategy:
      matrix:
        package: ['emacsD', 'emacsD-nogui', 'emacsD-pgtk']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: nixbuild/nix-quick-install-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix Store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: ${{ runner.os }}-build-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: ${{ runner.os }}-build-
          purge: true
          purge-created: 604800
          
      - name: Build
        run: nix build .#${{ matrix.package }} --print-build-logs

      - name: Setup cachix
        if: github.ref == 'refs/heads/main'
        run: nix profile install nixpkgs#cachix

      - name: Publish
        if: github.ref == 'refs/heads/main'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        run: cachix push brsvh ./result

      - name: Check configuration changes
        if: |
          github.ref == 'refs/heads/main' &&
          matrix.package == 'emacsD-nogui'
        uses: tj-actions/changed-files@v42
        id: check-changed-configs
        with:
          files: 'org/**.org'

      - name: Export configuration to Markdown
        id: ox-md
        if: |
          github.ref == 'refs/heads/main' &&
          matrix.package == 'emacsD-nogui' &&
          steps.check-changed-configs.outputs.any_changed == 'true'
        env:
          CONFIGS: ${{ steps.check-changed-configs.outputs.all_changed_files }}
        run: |
          for org in $CONFIGS
          do
             nix run .#batch -- $org --funcall org-md-export-to-markdown
          done

      - name: Check changed Markdown
        if: |
          github.ref == 'refs/heads/main' &&
          matrix.package == 'emacsD-nogui' &&
          steps.ox-md.outcome == 'success'
        uses: tj-actions/verify-changed-files@v17
        id: check-changed-docs
        with:
          files: 'docs/**.md'

      - name: Publish Markdown
        if: |
          github.ref == 'refs/heads/main' &&
          matrix.package == 'emacsD-nogui' &&
          steps.check-changed-docs.outputs.files_changed == 'true' 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto update"
          file_pattern: 'docs/**.md'
